### ISSUE TITLE
Received fatal alert: access_denied

### ISSUE THREAD

**Issue by spartacusX** [raydac/mvn-golang#27]
I am using maven behind an enterprise proxy, and encounter error as the title, the following is the maven log, any idea? thanks
env:
jdk: openjdk version "1.8.0_121"
maven: 3.3.9

log:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] suite-deployer-adaptor
[INFO] deployer-adaptor-binary
[INFO] itsma-deployer-adaptor
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building suite-deployer-adaptor 2017.11-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ suite-deployer-adaptor ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ suite-deployer-adaptor ---
[INFO] Installing /home/danny/src/golang/src/suite-deploy-adaptor/pom.xml to /home/danny/.m2/repository/com/hpe/itsma/suite-deployer-adaptor/2017.11-SNAPSHOT/suite-deployer-adaptor-2017.11-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building deployer-adaptor-binary 2017.11-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ deployer-adaptor-binary ---
[INFO] 
[INFO] --- mvn-golang-wrapper:2.1.6:run (default) @ deployer-adaptor-binary ---
[WARNING] Loading list of available GoLang SDKs from https://storage.googleapis.com/golang/
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] suite-deployer-adaptor ............................. SUCCESS [  0.211 s]
[INFO] deployer-adaptor-binary ............................ FAILURE [  0.954 s]
[INFO] itsma-deployer-adaptor ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.572 s
[INFO] Finished at: 2017-12-07T17:19:36+08:00
[INFO] Final Memory: 13M/205M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.1.6:run (default) on project deployer-adaptor-binary: Received fatal alert: access_denied -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :deployer-adaptor-binary

**Comment by raydac** [comment]
do you have tuned [maven to use your proxy](https://maven.apache.org/guides/mini/guide-proxies.html)? my plugin uses proxy parameters provided by maven, also it would be good to take a look at the log generated with `-X` option

**Comment by spartacusX** [comment]
The proxy works well, here's the log with -X option:

[DEBUG] Initing console out and console err buffers
[INFO] There is not any predefined SDK URL
[WARNING] Loading list of available GoLang SDKs from https://storage.googleapis.com/golang/
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] suite-deployer-adaptor ............................. SUCCESS [  0.196 s]
[INFO] deployer-adaptor-binary ............................ FAILURE [  1.074 s]
[INFO] itsma-deployer-adaptor ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.674 s
[INFO] Finished at: 2017-12-07T18:00:36+08:00
[INFO] Final Memory: 14M/259M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.1.6:run (default) on project deployer-adaptor-binary: Received fatal alert: access_denied -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.1.6:run (default) on project deployer-adaptor-binary: Received fatal alert: access_denied
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Received fatal alert: access_denied
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.execute(AbstractGolangMojo.java:1237)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.loadGoLangSdkList(AbstractGolangMojo.java:960)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.findSdkArchiveFileName(AbstractGolangMojo.java:1104)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.loadSDKAndUnpackIntoCache(AbstractGolangMojo.java:507)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.findGoRoot(AbstractGolangMojo.java:1151)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.prepareExecutor(AbstractGolangMojo.java:1349)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.doMainBusiness(AbstractGolangMojo.java:1185)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.execute(AbstractGolangMojo.java:1234)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :deployer-adaptor-binary

**Comment by raydac** [comment]
try please 2.1.7-SNAPSHOT version with parameter `<disableSSLcheck>true</disableSSLcheck>`, it should turn off check of SSL certificates during HTTP requests

**Comment by spartacusX** [comment]
Thanks raydac, but where can I get the version 2.1.7-SNAPSHOT?

**Comment by raydac** [comment]
just clone the repository `git clone https://github.com/raydac/mvn-golang.git` then start `mvn clean install -Pplugin` in the root of cloned folder, after build 2.1.7-SNAPSHOT will be presented in your local maven repository

**Comment by spartacusX** [comment]
with 2.1.7-SNAPSHOT and <disableSSLcheck>true</disableSSLcheck>, same error, here's the log:

[INFO] There is not any predefined SDK URL
[WARNING] Loading list of available GoLang SDKs from https://storage.googleapis.com/golang/?prefix=go1.8.2.linux-amd64
[WARNING] SSL certificate check has been disabled
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.522 s
[INFO] Finished at: 2017-12-08T17:21:53+08:00
[INFO] Final Memory: 11M/164M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.1.7-SNAPSHOT:run (default) on project deployer-adaptor-binary: Received fatal alert: access_denied -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.1.7-SNAPSHOT:run (default) on project deployer-adaptor-binary: Received fatal alert: access_denied
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Received fatal alert: access_denied
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.execute(AbstractGolangMojo.java:1313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.loadGoLangSdkList(AbstractGolangMojo.java:1030)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.findSdkArchiveFileName(AbstractGolangMojo.java:1178)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.loadSDKAndUnpackIntoCache(AbstractGolangMojo.java:542)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.findGoRoot(AbstractGolangMojo.java:1225)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.prepareExecutor(AbstractGolangMojo.java:1428)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.doMainBusiness(AbstractGolangMojo.java:1260)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.execute(AbstractGolangMojo.java:1309)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by spartacusX** [comment]
So sorry, raydac. I missed the configuration `<useMavenProxy>true</useMavenProxy>` in your first reply,  after added that, the plugin works perfectly.  many thanks.

**Comment by raydac** [comment]
cool! thanks a lot for the info!

**Comment by VaniRevanna** [comment]
@raydac can we build platform independent binary with maven golang build?

**Comment by raydac** [comment]
@VaniRevanna with mvn-golang plugin you can build everything what you can build with Go, Go doesn't produce uber-binary file which can be started everywhere, but you can generate specific binary file for each target OS like I make in [the project](https://github.com/raydac/zxtap-to-wav)
