### ISSUE TITLE
cannot run tests

### ISSUE THREAD

**Issue by bogdanpredescu** [raydac/mvn-golang#3]
[ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.0.0:test (default-test) on project myproject: Execution default-test of goal com.igormaznitsa:mvn-golang-wrapper:2.0.0:test failed: String index out of range: -1 
-> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.0.0:test (default-test) on project myproject: Execution default-test of goal com.igormaznitsa:mvn-golang-wrapper:2
.0.0:test failed: String index out of range: -1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal com.igormaznitsa:mvn-golang-wrapper:2.0.0:test failed: String index out of range: -1
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at com.igormaznitsa.mvngolang.GolangTestMojo.getPackages(GolangTestMojo.java:72)
	at com.igormaznitsa.mvngolang.AbstractPackageGolangMojo.getTailArguments(AbstractPackageGolangMojo.java:44)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.prepareExecutor(AbstractGolangMojo.java:1047)
	at com.igormaznitsa.mvngolang.AbstractGolangMojo.execute(AbstractGolangMojo.java:863)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 20 more

**Comment by raydac** [comment]
what is the absolute path to folder with tests? and what is the OS?

**Comment by bogdanpredescu** [comment]
D:\workspace\mymavenparentproject\myproject\src\program
Windows 7

It's a very basic project following the example available here on the site (math.go)

In the "program" folder there are two files:

program. go 

and

program_test.go which has this content (it actually doesn't test anything from the other file) :

package main

import (
	"testing"
)

func TestHelloWorld(t *testing.T) {
	str := HelloWorld("xxx")
	if str != "xxx" {
		t.Fail()
	}

}
