### ISSUE TITLE
Exception on macbook m1 arch

### ISSUE THREAD

**Issue by enuoCM** [raydac/mvn-golang#87]
Exception on macbook m1:
Exception in thread "main" java.lang.AssertionError: Can't recognize ARCH: aarch64
        at com.igormaznitsa.meta.common.utils.Assertions.assertNotNull(Assertions.java:125)
        at com.igormaznitsa.mvngolang.AbstractGolangMojo.getArch(AbstractGolangMojo.java:1100)

**Comment by raydac** [comment]
I have added auto-detect for aarch64, could you try the 2.3.9-SNAPSHOT version?

**Comment by enuoCM** [comment]
@raydac 2.3.9-SNAPSHOT is OK now. Thanks.
